baseURL = "http://sasinhe.com/"
paginate = 6
theme = "portio"
Title = 'Sasa Salmen'
defaultContentLanguage = 'pt-br'
defaultContentLanguageInSubdir = true
[languages]
  [languages.pt-br]
    contentDir = 'content/pt-br'
    disabled = false
    languageCode = 'pt-BR'
    languageDirection = 'ltr'
    languageName = 'Português'
    title = 'Sasa Salmen - Site Pessoal'
    weight = 1
    [languages.pt-br.params]
      subtitle = 'Blog, Portfolio e Tutoriais.'

    # Main Menu
    [[languages.pt-br.menu.main]]
    name = "Página Inicial"
    url = "#home"
    weight = 1
    [[languages.pt-br.menu.main]]
    name = "Sobre mim"
    url = "#about"
    weight = 2
    [[languages.pt-br.menu.main]]
    name = "Serviços"
    url = "#service"
    weight = 3
    [[languages.pt-br.menu.main]]
    name = "Portfolio"
    url = "#portfolio"
    weight = 4
    [[languages.pt-br.menu.main]]
    name = "Currículo"
    url = "#resume"
    weight = 5
    [[languages.pt-br.menu.main]]
    name = "Habilidades"
    url = "#skills"
    weight = 6
    [[languages.pt-br.menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 7
    [[languages.pt-br.menu.main]]
    name = "Contato"
    url = "#contact"
    weight = 8

  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Sasa Salmen - Personal Website'
    weight = 2

 # Main Menu
    [[languages.en.menu.main]]
    name = "Home"
    url = "#home"
    weight = 1
    [[languages.en.menu.main]]
    name = "About"
    url = "#about"
    weight = 2
    [[languages.en.menu.main]]
    name = "Services"
    url = "#service"
    weight = 3
    [[languages.en.menu.main]]
    name = "Portfolio"
    url = "#portfolio"
    weight = 4
    [[languages.en.menu.main]]
    name = "Work"
    url = "#resume"
    weight = 5
    [[languages.en.menu.main]]
    name = "Skills"
    url = "#skills"
    weight = 6
    [[languages.en.menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 7
    [[languages.en.menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 8


    [languages.en.params]
      subtitle = 'Blog, Portfolio and Tutorials'


# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/widget-logo.png"
# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/JpTXRUa"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
email = "sasinhe@gmail.com"
phone = "+55 (11) 99136-2886"


# Social icons
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/sasa-salmen-a7361b240"
weight = 2
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/sasinhe"
weight = 4
